apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-world-app-persistent-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/Users/fiveStars.user/fivestars/hello-world-app"
